import type { SpeakHandle, VoicePlayer } from './VoicePlayer';

/**
 * GoogleCloudVoicePlayer — narration via the server's /api/tts/google proxy.
 *
 * The proxy returns MP3 bytes generated by Google Cloud TTS (Neural2 by
 * default). We wrap the response in a blob URL and play it through an
 * HTMLAudioElement, so pause/resume/stop map to native media controls.
 *
 * Timing contract: `durationMs` starts as a word-count forecast (needed
 * synchronously by ScriptPlayer) and is refined to the true audio duration
 * once `loadedmetadata` fires. Consumers that care about exact end-of-audio
 * should await `done`, which resolves on the audio element's `ended` event.
 */

export interface GoogleCloudVoiceOptions {
  /** Base URL for the Showboxes server. Empty string = same origin. */
  serverUrl?: string;
  /** BCP-47 language code. Default "en-US". */
  languageCode?: string;
  /** Google voice name. Default "en-US-Neural2-F". */
  voiceName?: string;
  /** Pitch (-20..20). Default 0. */
  pitch?: number;
  /** Forecast words per minute used until real duration loads. Default 160. */
  wordsPerMinute?: number;
}

interface Active {
  audio: HTMLAudioElement;
  url: string;
  resolveDone: () => void;
  handle: SpeakHandle;
}

export class GoogleCloudVoicePlayer implements VoicePlayer {
  private opts: Required<Omit<GoogleCloudVoiceOptions, 'serverUrl'>> & {
    serverUrl: string;
  };
  private active: Active | null = null;

  constructor(opts: GoogleCloudVoiceOptions = {}) {
    this.opts = {
      serverUrl: (opts.serverUrl ?? '').replace(/\/$/, ''),
      languageCode: opts.languageCode ?? 'en-US',
      voiceName: opts.voiceName ?? 'en-US-Neural2-F',
      pitch: opts.pitch ?? 0,
      wordsPerMinute: opts.wordsPerMinute ?? 160,
    };
  }

  speak(text: string, opts?: { speed?: number }): SpeakHandle {
    this.stop();

    const speed = opts?.speed ?? 1.0;
    const words = Math.max(1, text.trim().split(/\s+/).length);
    const forecast = Math.round((words / this.opts.wordsPerMinute) * 60_000 / speed);

    const audio = new Audio();
    audio.preload = 'auto';

    let resolveDone!: () => void;
    const done = new Promise<void>((r) => (resolveDone = r));

    const handle: SpeakHandle = {
      durationMs: forecast,
      hasAccurateDuration: false,
      done,
      cancel: () => this.stop(),
    };

    audio.addEventListener('loadedmetadata', () => {
      if (this.active?.audio !== audio) return;
      if (isFinite(audio.duration) && audio.duration > 0) {
        handle.durationMs = Math.round(audio.duration * 1000);
        handle.hasAccurateDuration = true;
      }
    });

    const settle = () => {
      if (this.active?.audio !== audio) return;
      this.teardownActive();
      resolveDone();
    };
    audio.addEventListener('ended', settle);
    audio.addEventListener('error', settle);

    const active: Active = { audio, url: '', resolveDone, handle };
    this.active = active;

    // Fire the fetch + playback async — handle is returned synchronously.
    void this.loadAndPlay(text, speed, active);

    return handle;
  }

  pause(): void {
    this.active?.audio.pause();
  }

  resume(): void {
    void this.active?.audio.play().catch(() => {});
  }

  stop(): void {
    const a = this.active;
    if (!a) return;
    this.active = null;
    try {
      a.audio.pause();
      a.audio.src = '';
    } catch {
      // ignore
    }
    if (a.url) URL.revokeObjectURL(a.url);
    a.resolveDone();
  }

  private teardownActive(): void {
    const a = this.active;
    if (!a) return;
    this.active = null;
    if (a.url) URL.revokeObjectURL(a.url);
  }

  private async loadAndPlay(text: string, speed: number, active: Active): Promise<void> {
    try {
      const res = await fetch(`${this.opts.serverUrl}/api/tts/google`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text,
          voiceName: this.opts.voiceName,
          languageCode: this.opts.languageCode,
          speed,
          pitch: this.opts.pitch,
        }),
      });

      if (!res.ok) {
        const detail = await res.text().catch(() => '');
        throw new Error(`TTS ${res.status}: ${detail.slice(0, 200)}`);
      }

      const blob = await res.blob();
      if (this.active !== active) return; // cancelled mid-flight

      const url = URL.createObjectURL(blob);
      active.url = url;
      active.audio.src = url;
      await active.audio.play();
    } catch (err) {
      console.error('[GoogleCloudVoicePlayer] playback failed:', err);
      if (this.active === active) {
        this.teardownActive();
        active.resolveDone();
      }
    }
  }
}
