// Tool Provider Registry
// Maps MetricSource credentials to available agent tools.
// Each provider defines read and/or write tools for its platform.

import type { ToolProvider, ToolProviderType, ResolvedTool } from "../types";
import type { MetricSource } from "@prisma/client";
import type { PrismaClient } from "@prisma/client";

// ── Provider Registry ─────────────────────────────────────

const providers = new Map<ToolProviderType, ToolProvider>();

export function registerToolProvider(provider: ToolProvider) {
  providers.set(provider.type, provider);
}

export function getToolProvider(type: ToolProviderType): ToolProvider | undefined {
  return providers.get(type);
}

export function getAllProviders(): ToolProvider[] {
  return Array.from(providers.values());
}

// ── Tool Resolution ───────────────────────────────────────

/**
 * Given a set of available credentials (from MetricsConfig),
 * resolve all tools the agent can use.
 */
export function resolveToolsFromCredentials(
  requestedProviders: ToolProviderType[],
  credentials: Map<MetricSource, { creds: Record<string, unknown>; meta?: Record<string, unknown> }>,
): ResolvedTool[] {
  const tools: ResolvedTool[] = [];

  for (const providerType of requestedProviders) {
    const provider = providers.get(providerType);
    if (!provider) continue;

    // Check if we have credentials for any of the required sources
    for (const source of provider.requiredSources) {
      const credEntry = credentials.get(source);
      if (credEntry) {
        tools.push(...provider.resolveTools(credEntry.creds, credEntry.meta));
        break; // only resolve once per provider
      }
    }
  }

  // Always include built-in tools that don't need credentials
  tools.push(...getBuiltInTools(requestedProviders));

  return tools;
}

// ── Built-in Tools (no credentials needed) ────────────────

function getBuiltInTools(requestedProviders: ToolProviderType[]): ResolvedTool[] {
  const tools: ResolvedTool[] = [];

  if (requestedProviders.includes("content_generation")) {
    tools.push({
      name: "generate_content",
      description: "Generate marketing content (social media post, email copy, blog outline, etc.). Specify the type, platform, tone, and key points.",
      input_schema: {
        type: "object",
        properties: {
          content_type: { type: "string", enum: ["social_post", "email", "blog_outline", "ad_copy", "press_release", "discord_message"] },
          platform: { type: "string", description: "Target platform (twitter, instagram, linkedin, etc.)" },
          tone: { type: "string", description: "Desired tone (professional, casual, excited, informative)" },
          key_points: { type: "array", items: { type: "string" }, description: "Key points to include" },
          max_length: { type: "number", description: "Maximum character length" },
          hashtags: { type: "boolean", description: "Whether to include hashtags" },
        },
        required: ["content_type", "key_points"],
      },
      provider: "content_generation",
      hasSideEffects: false,
      execute: async (input) => {
        // This is handled by the LLM itself — the tool call signals intent
        return { type: "content_generation", input, note: "Content will be generated by the LLM in the next reasoning step" };
      },
    });
  }

  if (requestedProviders.includes("data_analysis")) {
    tools.push({
      name: "analyze_metrics",
      description: "Analyze metric trends and generate insights. Provide the metrics data and the type of analysis desired.",
      input_schema: {
        type: "object",
        properties: {
          metrics: { type: "array", items: { type: "object" }, description: "Array of metric data points" },
          analysis_type: { type: "string", enum: ["trend", "comparison", "anomaly_detection", "forecast", "summary"] },
          period: { type: "string", description: "Time period to analyze (e.g. 'last_7_days', 'last_30_days')" },
        },
        required: ["metrics", "analysis_type"],
      },
      provider: "data_analysis",
      hasSideEffects: false,
      execute: async (input) => {
        return { type: "data_analysis", input, note: "Analysis will be performed by the LLM" };
      },
    });

    tools.push({
      name: "record_metric",
      description: "Record a new metric data point for this tactic. Use after fetching fresh data from a platform.",
      input_schema: {
        type: "object",
        properties: {
          source: { type: "string", description: "Metric source (TWITTER, STEAM, etc.)" },
          metric: { type: "string", description: "Metric name (followers, wishlists, etc.)" },
          value: { type: "number", description: "The metric value" },
          unit: { type: "string", description: "Unit of measurement" },
        },
        required: ["source", "metric", "value"],
      },
      provider: "data_analysis",
      hasSideEffects: true,
      execute: async (input) => {
        // This will be intercepted by the agent runtime and routed to MetricService
        return { type: "record_metric", ...input };
      },
    });
  }

  if (requestedProviders.includes("web_search")) {
    tools.push({
      name: "web_search",
      description: "Search the web for information relevant to the task. Use for competitor analysis, trend research, or finding opportunities.",
      input_schema: {
        type: "object",
        properties: {
          query: { type: "string", description: "Search query" },
          num_results: { type: "number", description: "Number of results to return (max 10)" },
        },
        required: ["query"],
      },
      provider: "web_search",
      hasSideEffects: false,
      execute: async (input) => {
        // Will be implemented with a search API (Tavily, Serper, etc.)
        return { type: "web_search", query: input.query, note: "Web search integration pending" };
      },
    });

    // ── Page Content Fetching (Browserless.io) ─────────────
    //
    // Retrieves fully-rendered HTML from a URL using headless Chrome.
    // Essential for the Research Gnome's source monitoring — fetches
    // dynamic content (SPAs, Reddit, HN, forums) that raw HTTP can't.
    // Also useful for any gnome that needs to read a live web page.

    tools.push({
      name: "fetch_page_content",
      description:
        "Fetch the fully-rendered HTML content of a web page using headless Chrome (via Browserless.io). " +
        "Returns the page's rendered DOM — use this instead of raw HTTP requests to handle JavaScript-rendered " +
        "sites like Reddit, Hacker News, forums, and SPAs. Essential for monitoring sources and extracting " +
        "content from dynamic pages. The returned HTML can then be parsed to extract articles, discussions, " +
        "comments, upvote counts, and other structured content.",
      input_schema: {
        type: "object",
        properties: {
          url: {
            type: "string",
            description: "The URL to fetch (e.g. 'https://news.ycombinator.com', 'https://www.reddit.com/r/fintech/hot').",
          },
          waitForSelector: {
            type: "string",
            description:
              "Optional CSS selector to wait for before returning content. " +
              "Use when the page loads content dynamically (e.g. '.Post' for Reddit, '.athing' for HN).",
          },
          waitUntil: {
            type: "string",
            enum: ["load", "domcontentloaded", "networkidle0", "networkidle2"],
            description: "When to consider the page loaded. Default: 'networkidle2' (recommended for most sites).",
          },
        },
        required: ["url"],
      },
      provider: "web_search",
      hasSideEffects: false,
      execute: async (input) => {
        const { fetchPageContent, isConfigured } = await import("@/services/screenshot.service");

        if (!isConfigured()) {
          return {
            error: true,
            message:
              "Browserless.io is not configured. Set BROWSERLESS_API_KEY to enable page content fetching.",
          };
        }

        try {
          const result = await fetchPageContent(input.url as string, {
            waitForSelector: (input.waitForSelector as string) ?? undefined,
            waitUntil: (input.waitUntil as "load" | "domcontentloaded" | "networkidle0" | "networkidle2") ?? undefined,
          });

          // Truncate very large pages to avoid blowing up context windows.
          // 100k chars is roughly 25k tokens — generous but bounded.
          const MAX_CONTENT_LENGTH = 100_000;
          const html = result.html.length > MAX_CONTENT_LENGTH
            ? result.html.slice(0, MAX_CONTENT_LENGTH) + "\n\n[... content truncated at 100k characters ...]"
            : result.html;

          return {
            url: result.url,
            contentLength: result.html.length,
            truncated: result.html.length > MAX_CONTENT_LENGTH,
            html,
          };
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          return {
            error: true,
            url: input.url,
            message: `Failed to fetch page content: ${message}`,
          };
        }
      },
    });

    // ── Content Extraction & Analysis ────────────────────────
    //
    // Takes raw HTML (from fetch_page_content) and extracts structured
    // data. The LLM does the actual parsing — this tool signals intent
    // and provides guidance on what to extract.

    tools.push({
      name: "extract_content",
      description:
        "Extract and structure content from raw HTML. Provide the HTML (from fetch_page_content) " +
        "and specify what to extract — the LLM will parse the HTML and return structured data. " +
        "Use this to turn a fetched page into actionable data: top discussions, trending topics, " +
        "comment sentiment, article summaries, etc.",
      input_schema: {
        type: "object",
        properties: {
          html: {
            type: "string",
            description: "The raw HTML content to extract from (from fetch_page_content result).",
          },
          sourceUrl: {
            type: "string",
            description: "The URL this HTML came from (for attribution).",
          },
          extractionGoal: {
            type: "string",
            description:
              "What to extract from the page. Be specific. Examples: " +
              "'top 10 posts by upvotes with titles, scores, and comment counts', " +
              "'all comments mentioning community banking or fintech', " +
              "'article headlines and summaries from the front page', " +
              "'user questions and complaints about banking software'.",
          },
          format: {
            type: "string",
            enum: ["list", "table", "summary", "signals"],
            description:
              "Output format. 'list' = array of items, 'table' = rows and columns, " +
              "'summary' = prose summary, 'signals' = pre-classified trend signals.",
          },
        },
        required: ["html", "extractionGoal"],
      },
      provider: "web_search",
      hasSideEffects: false,
      execute: async (input) => {
        // Like content_generation, this is handled by the LLM's reasoning.
        // The tool call structures the intent so the LLM produces focused output.
        return {
          type: "content_extraction",
          sourceUrl: input.sourceUrl,
          extractionGoal: input.extractionGoal,
          format: input.format ?? "signals",
          note: "Content extraction will be performed by the LLM in the next reasoning step.",
        };
      },
    });
  }

  // ── Media Library Tools ─────────────────────────────────
  //
  // Two tools for gnomes to work with the media library:
  //
  //  1. request_media_design — open a designer request: creates a MediaAsset
  //     in REQUESTED status, spawns a sibling Task assigned to the designer
  //     gnome, and optionally attaches the (pending) asset to the current
  //     work product so readyToDeliver gates delivery until the image lands.
  //
  //  2. capture_screenshot — synchronously capture a screenshot, create a
  //     MediaAsset (DRAFT or APPROVED), and optionally attach it to the
  //     current work product. Uses Playwright under the hood.
  //
  //  3. browse_media_library — search approved assets by tags/title so the
  //     gnome can pick an existing image to attach.
  //
  //  4. attach_media — attach an existing approved MediaAsset to the current
  //     work product by its ID.

  if (requestedProviders.includes("media_library")) {
    tools.push({
      name: "browse_media_library",
      description:
        "Search the project's approved media library for images matching the given tags " +
        "or title keywords. Use this before creating new images to check what's already available. " +
        "Returns a list of approved media assets with their IDs, titles, tags, and image URLs.",
      input_schema: {
        type: "object",
        properties: {
          projectSlug: {
            type: "string",
            description: "The project slug (from your context)",
          },
          tags: {
            type: "array",
            items: { type: "string" },
            description: "Tags to filter by (e.g. ['hero', 'screenshot', 'dashboard']). Returns assets matching ANY of these tags.",
          },
        },
        required: ["projectSlug"],
      },
      provider: "media_library",
      hasSideEffects: false,
      execute: async (input) => {
        const { MediaService } = await import("@/services");
        const assets = await MediaService.listMediaAssets({
          projectSlug: input.projectSlug as string,
          status: "APPROVED",
          tags: (input.tags as string[]) ?? undefined,
        });
        return {
          count: assets.length,
          assets: assets.map((a: (typeof assets)[number]) => ({
            id: a.id,
            title: a.title,
            slug: a.slug,
            imageUrl: a.imageUrl,
            thumbnailUrl: a.thumbnailUrl,
            tags: a.tags,
            description: a.description,
            contentHash: a.contentHash,
            mimeType: a.mimeType,
            width: a.width,
            height: a.height,
          })),
        };
      },
    });

    tools.push({
      name: "attach_media",
      description:
        "Attach an existing media asset to the current work product. " +
        "Call browse_media_library first to find assets, then use this to attach one by ID. " +
        "You can optionally provide alt text for accessibility. " +
        "If the work product hasn't been created yet, provide executionId and the " +
        "attachment will be queued and applied automatically when you submit the work product.",
      input_schema: {
        type: "object",
        properties: {
          workProductId: {
            type: "string",
            description: "The ID of the current work product (if it exists already)",
          },
          executionId: {
            type: "string",
            description: "The execution ID (from your context). Used to queue the attachment if the work product doesn't exist yet.",
          },
          mediaAssetId: {
            type: "string",
            description: "The ID of the media asset to attach (from browse_media_library results)",
          },
          altText: {
            type: "string",
            description: "Alt text for the image in this specific usage (for accessibility)",
          },
        },
        required: ["mediaAssetId"],
      },
      provider: "media_library",
      hasSideEffects: true,
      execute: async (input) => {
        const { MediaAttachmentService } = await import("@/services");
        const { prisma: db } = await import("@/lib/prisma") as { prisma: PrismaClient };
        const mediaAssetId = input.mediaAssetId as string;
        const workProductId = input.workProductId as string | undefined;
        const executionId = input.executionId as string | undefined;
        const altText = (input.altText as string) ?? undefined;

        // Try direct attachment if workProductId is provided
        if (workProductId) {
          try {
            const attachment = await MediaAttachmentService.attachMedia({
              workProductId,
              mediaAssetId,
              altText,
              source: "GNOME_SUGGESTED",
            });
            const att = attachment as typeof attachment & { mediaAsset?: { title?: string; imageUrl?: string | null } };
            return {
              attached: true,
              queued: false,
              attachmentId: attachment.id,
              mediaAssetTitle: att.mediaAsset?.title ?? null,
              imageUrl: att.mediaAsset?.imageUrl ?? null,
            };
          } catch {
            // WorkProduct might not exist yet — fall through to queue
          }
        }

        // Queue the attachment on the execution for auto-attach after submit_work_product
        if (executionId) {
          await db.taskExecution.update({
            where: { id: executionId },
            data: {
              pendingMediaIds: { push: mediaAssetId },
            },
          });
          return {
            attached: false,
            queued: true,
            mediaAssetId,
            note: "Media queued — will be attached automatically when the work product is submitted.",
          };
        }

        return {
          attached: false,
          queued: false,
          error: "Provide either workProductId or executionId to attach media.",
        };
      },
    });

    tools.push({
      name: "request_media_design",
      description:
        "Request a new image to be designed or generated. Creates a media asset in " +
        "REQUESTED status with your design brief, creates a sibling task assigned to the " +
        "designer gnome, and attaches the (pending) asset to the current work product. " +
        "Delivery of the work product will be gated until the image is approved. " +
        "Use this when browse_media_library returns nothing suitable and you need a " +
        "custom image for the post.",
      input_schema: {
        type: "object",
        properties: {
          projectSlug: {
            type: "string",
            description: "The project slug",
          },
          tacticId: {
            type: "string",
            description: "The tactic ID (from your context) — the new designer task will be added to this tactic",
          },
          workProductId: {
            type: "string",
            description: "The ID of the current work product to attach the image to (optional — omit if this is just a general request)",
          },
          executionId: {
            type: "string",
            description: "The execution ID (from your context). Used to queue the attachment if the work product doesn't exist yet.",
          },
          title: {
            type: "string",
            description: "Short title for the media asset (e.g. 'Ohio map dashboard screenshot')",
          },
          brief: {
            type: "string",
            description:
              "Detailed design brief describing what image is needed, including style, mood, " +
              "dimensions, key elements, and how it will be used in the post. Be specific enough " +
              "that a designer or AI generator can produce the image without additional context.",
          },
          tags: {
            type: "array",
            items: { type: "string" },
            description: "Tags for the requested asset (e.g. ['hero', 'screenshot', 'map'])",
          },
          designerGnomeSlug: {
            type: "string",
            description: "Slug of the designer gnome to assign. Defaults to 'designer-gnome'.",
          },
        },
        required: ["projectSlug", "tacticId", "title", "brief"],
      },
      provider: "media_library",
      hasSideEffects: true,
      execute: async (input) => {
        const { MediaService, MediaAttachmentService } = await import("@/services");
        const { prisma: db } = await import("@/lib/prisma") as { prisma: PrismaClient };

        const projectSlug = input.projectSlug as string;
        const tacticId = input.tacticId as string;
        const title = input.title as string;
        const brief = input.brief as string;
        const tags = (input.tags as string[]) ?? [];
        const workProductId = input.workProductId as string | undefined;
        const executionId = input.executionId as string | undefined;
        const designerSlug = (input.designerGnomeSlug as string) ?? "designer-gnome";

        // 1. Create the MediaAsset in REQUESTED status
        const asset = await MediaService.createMediaAsset({
          projectSlug,
          title,
          description: brief,
          tags,
          status: "REQUESTED",
          requestBrief: brief,
          sourceType: "DESIGNER_REQUEST",
        });

        // 2. Create a sibling Task on the same tactic, assigned to the designer gnome.
        //    assigneeId holds the gnome slug; assignAgent() resolves it via resolveAgentBySlug().
        const task = await db.task.create({
          data: {
            tacticId,
            title: `Design: ${title}`,
            description:
              `Create an image based on this brief:\n\n${brief}\n\n` +
              `The resulting image should be saved to media asset ${asset.id} ("${title}").`,
            status: "TODO",
            assigneeType: "AGENT",
            assigneeId: designerSlug,
            priority: "MEDIUM",
          },
        });

        // 3. Attach the (pending) asset to the work product, or queue for later
        let attachmentId: string | undefined;
        let queued = false;
        if (workProductId) {
          try {
            const att = await MediaAttachmentService.attachMedia({
              workProductId,
              mediaAssetId: asset.id,
              source: "GNOME_SUGGESTED",
            });
            attachmentId = att.id;
          } catch {
            // WorkProduct doesn't exist yet — fall through to queue
          }
        }
        if (!attachmentId && executionId) {
          await db.taskExecution.update({
            where: { id: executionId },
            data: { pendingMediaIds: { push: asset.id } },
          });
          queued = true;
        }

        return {
          mediaAssetId: asset.id,
          mediaAssetSlug: asset.slug,
          designerTaskId: task.id,
          designerGnomeSlug: designerSlug,
          attachmentId: attachmentId ?? null,
          queued,
          note:
            `Design request opened. Task "${task.title}" assigned to ${designerSlug}. ` +
            (queued
              ? `Media attachment queued — will be linked when work product is submitted. `
              : ``) +
            `The work product delivery will wait until the image is approved.`,
        };
      },
    });

    tools.push({
      name: "capture_screenshot",
      description:
        "Capture a screenshot of a web page or specific element. Creates a media asset " +
        "with the captured image. Useful for product screenshots, dashboard views, " +
        "landing pages, etc. The screenshot is stored as a DRAFT media asset — " +
        "a human will need to approve it before it can be used in delivery.",
      input_schema: {
        type: "object",
        properties: {
          projectSlug: {
            type: "string",
            description: "The project slug",
          },
          url: {
            type: "string",
            description: "Full URL to capture (e.g. 'https://solostates.solostream.io/dashboard')",
          },
          title: {
            type: "string",
            description: "Title for the captured asset (e.g. 'SoloStates dashboard overview')",
          },
          selector: {
            type: "string",
            description: "Optional CSS selector to capture a specific element instead of the full page (e.g. '#map-container')",
          },
          viewport: {
            type: "object",
            properties: {
              width: { type: "number", description: "Viewport width in pixels (default 1280)" },
              height: { type: "number", description: "Viewport height in pixels (default 720)" },
            },
          },
          waitForSelector: {
            type: "string",
            description: "CSS selector to wait for before capturing (for dynamic content)",
          },
          delayMs: {
            type: "number",
            description: "Additional delay in ms after page load before capturing (for animations)",
          },
          tags: {
            type: "array",
            items: { type: "string" },
            description: "Tags for the captured asset",
          },
          workProductId: {
            type: "string",
            description: "If provided, auto-attach the screenshot to this work product",
          },
          executionId: {
            type: "string",
            description: "The execution ID (from your context). Used to queue the attachment if the work product doesn't exist yet.",
          },
        },
        required: ["projectSlug", "url", "title"],
      },
      provider: "media_library",
      hasSideEffects: true,
      execute: async (input) => {
        const { MediaService, MediaAttachmentService, StorageService } = await import("@/services");
        const { captureScreenshot } = await import("@/services/screenshot.service");

        const projectSlug = input.projectSlug as string;
        const url = input.url as string;
        const title = input.title as string;
        const tags = (input.tags as string[]) ?? ["screenshot"];
        const workProductId = input.workProductId as string | undefined;
        const executionId = input.executionId as string | undefined;

        const captureSpec = {
          url,
          selector: (input.selector as string) ?? null,
          viewport: (input.viewport as { width: number; height: number }) ?? { width: 1280, height: 720 },
          waitForSelector: (input.waitForSelector as string) ?? null,
          delayMs: (input.delayMs as number) ?? 0,
        };

        // 1. Create the MediaAsset in REQUESTED status (so it exists even if capture fails)
        const asset = await MediaService.createMediaAsset({
          projectSlug,
          title,
          description: `Screenshot of ${url}`,
          tags: [...tags, "screenshot"],
          status: "REQUESTED",
          requestBrief: JSON.stringify(captureSpec, null, 2),
          sourceType: "SCREENSHOT_GNOME",
          sourceUrl: url,
        });

        // 2. Capture the screenshot with Playwright
        let screenshotResult;
        try {
          screenshotResult = await captureScreenshot(captureSpec);
        } catch (err) {
          return {
            mediaAssetId: asset.id,
            status: "REQUESTED",
            error: true,
            message: `Screenshot capture failed: ${err instanceof Error ? err.message : String(err)}`,
            note: "The media asset was created in REQUESTED status. You can retry or use generate_image as a fallback.",
          };
        }

        // 3. Upload to R2 if configured, otherwise use a data URL fallback
        let imageUrl: string;
        let storageKey: string | undefined;
        let contentHash: string | undefined;

        if (StorageService.isConfigured()) {
          const key = `media/${projectSlug}/${asset.id}/screenshot.png`;
          const upload = await StorageService.uploadBuffer(
            screenshotResult.buffer,
            key,
            "image/png",
          );
          imageUrl = upload.publicUrl;
          storageKey = upload.storageKey;
          contentHash = upload.contentHash;
        } else {
          // Fallback: base64 data URL (capped at ~4MB to be safe)
          if (screenshotResult.buffer.length > 4 * 1024 * 1024) {
            return {
              mediaAssetId: asset.id,
              status: "REQUESTED",
              error: true,
              message: "Screenshot too large for data URL fallback. Configure R2 storage.",
            };
          }
          imageUrl = `data:image/png;base64,${screenshotResult.buffer.toString("base64")}`;
        }

        // 4. Update the asset to DRAFT with the captured image
        const updated = await MediaService.updateMediaAsset(asset.id, {
          imageUrl,
          storageKey,
          contentHash,
          mimeType: "image/png",
          width: screenshotResult.width,
          height: screenshotResult.height,
          sizeBytes: screenshotResult.buffer.length,
          status: "DRAFT",
        });

        // 5. Attach to work product if requested
        let attachmentId: string | undefined;
        let queued = false;
        if (workProductId) {
          try {
            const att = await MediaAttachmentService.attachMedia({
              workProductId,
              mediaAssetId: asset.id,
              source: "GNOME_SUGGESTED",
            });
            attachmentId = att.id;
          } catch {
            // WorkProduct doesn't exist yet — fall through to queue
          }
        }
        if (!attachmentId && executionId) {
          const { prisma: db } = await import("@/lib/prisma") as { prisma: PrismaClient };
          await db.taskExecution.update({
            where: { id: executionId },
            data: { pendingMediaIds: { push: asset.id } },
          });
          queued = true;
        }

        return {
          mediaAssetId: asset.id,
          status: "DRAFT",
          imageUrl: updated.imageUrl,
          storageKey: storageKey ?? null,
          width: screenshotResult.width,
          height: screenshotResult.height,
          sizeBytes: screenshotResult.buffer.length,
          attachmentId: attachmentId ?? null,
          queued,
          note:
            `Screenshot captured and saved as DRAFT media asset "${title}". ` +
            (storageKey ? `Stored in R2 at ${storageKey}. ` : "") +
            "A human will need to approve it before delivery.",
        };
      },
    });
  }

  // ── AI Image Generation Tools ───────────────────────────
  //
  // Tools for the designer gnome to generate images via Flux (FAL.ai)
  // and update media assets with the results.
  //
  // Requires FAL_KEY env var. The generate_image tool calls the FAL.ai
  // REST API for Flux Pro, waits for the result, and returns the image URL.
  // The update_media_asset tool writes the generated image back to the
  // media library.

  if (requestedProviders.includes("ai_image_generation")) {
    tools.push({
      name: "generate_image",
      description:
        "Generate an image using AI (Flux Pro via FAL.ai). Provide a detailed text prompt " +
        "describing the desired image. Returns the generated image URL. You can specify " +
        "dimensions and a seed for reproducibility.",
      input_schema: {
        type: "object",
        properties: {
          prompt: {
            type: "string",
            description:
              "Detailed text prompt for the image. Be specific about subject, style, " +
              "composition, colors, lighting, and mood. Example: 'A clean, modern dashboard " +
              "interface showing a US map with highlighted community bank locations in green, " +
              "dark background, professional infographic style, no text overlays'",
          },
          width: {
            type: "number",
            description: "Image width in pixels. Common sizes: 1200 (LinkedIn), 1080 (Instagram square)",
          },
          height: {
            type: "number",
            description: "Image height in pixels. Common sizes: 627 (LinkedIn), 1080 (Instagram square)",
          },
          seed: {
            type: "number",
            description: "Random seed for reproducible results. Use the same seed to get similar outputs when iterating on a prompt.",
          },
          num_images: {
            type: "number",
            description: "Number of images to generate (default 1, max 4). Useful for giving the reviewer options.",
          },
        },
        required: ["prompt"],
      },
      provider: "ai_image_generation",
      hasSideEffects: true,
      execute: async (input) => {
        const falKey = process.env.FAL_KEY;
        if (!falKey) {
          return {
            error: true,
            message:
              "FAL_KEY environment variable is not set. Please add your FAL.ai API key " +
              "to the environment to enable AI image generation.",
          };
        }

        const prompt = input.prompt as string;
        const width = (input.width as number) ?? 1200;
        const height = (input.height as number) ?? 627;
        const seed = input.seed as number | undefined;
        const numImages = Math.min((input.num_images as number) ?? 1, 4);

        try {
          // Submit generation request to FAL.ai Flux Pro
          const submitRes = await fetch("https://queue.fal.run/fal-ai/flux-pro/v1.1", {
            method: "POST",
            headers: {
              Authorization: `Key ${falKey}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              prompt,
              image_size: { width, height },
              num_images: numImages,
              ...(seed !== undefined ? { seed } : {}),
              enable_safety_checker: true,
            }),
          });

          if (!submitRes.ok) {
            const errBody = await submitRes.text();
            return { error: true, message: `FAL.ai submit failed (${submitRes.status}): ${errBody}` };
          }

          const submitData = await submitRes.json();

          // FAL queue returns a request_id + status_url for async polling
          const requestId = submitData.request_id;
          const statusUrl = submitData.status_url || `https://queue.fal.run/fal-ai/flux-pro/requests/${requestId}/status`;

          // Poll for completion (up to 60 seconds)
          const maxWait = 60_000;
          const pollInterval = 2_000;
          const start = Date.now();

          while (Date.now() - start < maxWait) {
            await new Promise((r) => setTimeout(r, pollInterval));

            const statusRes = await fetch(statusUrl, {
              headers: { Authorization: `Key ${falKey}` },
            });

            if (!statusRes.ok) continue;
            const statusData = await statusRes.json();

            if (statusData.status === "COMPLETED") {
              // Fetch the actual result using FAL's response_url (the path
              // differs from the submit endpoint — no version suffix)
              const resultUrl = statusData.response_url
                ?? `https://queue.fal.run/fal-ai/flux-pro/requests/${requestId}`;
              const resultRes = await fetch(resultUrl, {
                headers: { Authorization: `Key ${falKey}` },
              });

              if (!resultRes.ok) {
                return { error: true, message: "Failed to fetch generation result" };
              }

              const resultData = await resultRes.json();
              const images = resultData.images ?? [];

              return {
                success: true,
                images: images.map((img: { url: string; width?: number; height?: number; content_type?: string }, i: number) => ({
                  index: i,
                  url: img.url,
                  width: img.width ?? width,
                  height: img.height ?? height,
                  contentType: img.content_type ?? "image/jpeg",
                })),
                seed: resultData.seed,
                prompt,
                requestId,
                note: `Generated ${images.length} image(s). Use update_media_asset to save the chosen image to the media library.`,
              };
            }

            if (statusData.status === "FAILED") {
              return { error: true, message: `Image generation failed: ${statusData.error || "Unknown error"}` };
            }
          }

          return { error: true, message: "Image generation timed out after 60 seconds" };
        } catch (err) {
          return { error: true, message: `Image generation error: ${err instanceof Error ? err.message : String(err)}` };
        }
      },
    });

    tools.push({
      name: "update_media_asset",
      description:
        "Update an existing media asset in the library. Use this after generate_image to " +
        "save the generated image URL to a REQUESTED media asset, transitioning it to DRAFT " +
        "status. Also use to update tags, description, or other metadata.",
      input_schema: {
        type: "object",
        properties: {
          mediaAssetId: {
            type: "string",
            description: "The ID of the media asset to update",
          },
          imageUrl: {
            type: "string",
            description: "The generated image URL to set",
          },
          thumbnailUrl: {
            type: "string",
            description: "Optional thumbnail URL",
          },
          status: {
            type: "string",
            enum: ["REQUESTED", "IN_PROGRESS", "DRAFT", "APPROVED", "ARCHIVED"],
            description: "New status. Typically set to DRAFT after generating an image.",
          },
          description: {
            type: "string",
            description: "Updated description",
          },
          tags: {
            type: "array",
            items: { type: "string" },
            description: "Updated tags",
          },
          width: { type: "number", description: "Image width in pixels" },
          height: { type: "number", description: "Image height in pixels" },
          mimeType: { type: "string", description: "MIME type (e.g. 'image/jpeg')" },
          contentHash: { type: "string", description: "SHA-256 hash of image bytes if known" },
          sourceType: {
            type: "string",
            enum: ["MANUAL", "UPLOAD", "SCREENSHOT_GNOME", "AI_GNOME", "DESIGNER_REQUEST", "EXTERNAL_LINK"],
            description: "How this image was produced. Typically AI_GNOME for generated images.",
          },
        },
        required: ["mediaAssetId"],
      },
      provider: "ai_image_generation",
      hasSideEffects: true,
      execute: async (input) => {
        const { MediaService, StorageService } = await import("@/services");
        const id = input.mediaAssetId as string;

        const updateData: Record<string, unknown> = {};
        if (input.imageUrl !== undefined) updateData.imageUrl = input.imageUrl;
        if (input.thumbnailUrl !== undefined) updateData.thumbnailUrl = input.thumbnailUrl;
        if (input.status !== undefined) updateData.status = input.status;
        if (input.description !== undefined) updateData.description = input.description;
        if (input.tags !== undefined) updateData.tags = input.tags;
        if (input.width !== undefined) updateData.width = input.width;
        if (input.height !== undefined) updateData.height = input.height;
        if (input.mimeType !== undefined) updateData.mimeType = input.mimeType;
        if (input.contentHash !== undefined) updateData.contentHash = input.contentHash;
        if (input.sourceType !== undefined) updateData.sourceType = input.sourceType;

        // Persist external image URLs to R2 (FAL.ai URLs expire quickly)
        const imageUrl = input.imageUrl as string | undefined;
        if (imageUrl?.startsWith("http") && StorageService.isConfigured()) {
          try {
            const key = `media/${id}/generated.jpg`;
            const upload = await StorageService.uploadFromUrl(imageUrl, key);
            updateData.imageUrl = upload.publicUrl;
            updateData.storageKey = upload.storageKey;
            updateData.sizeBytes = upload.sizeBytes;
            updateData.contentHash = upload.contentHash;
          } catch (err) {
            // Non-fatal: keep the original external URL if R2 upload fails
            console.warn(`[update_media_asset] R2 upload failed, keeping external URL: ${err instanceof Error ? err.message : String(err)}`);
          }
        }

        const updated = await MediaService.updateMediaAsset(id, updateData as Parameters<typeof MediaService.updateMediaAsset>[1]);

        return {
          success: true,
          mediaAssetId: updated.id,
          title: updated.title,
          status: updated.status,
          imageUrl: updated.imageUrl,
          storedInR2: !!updated.storageKey,
          note: `Media asset "${updated.title}" updated to status ${updated.status}.` +
            (updated.storageKey ? ` Image persisted to R2.` : ``),
        };
      },
    });
  }

  return tools;
}

// ── Register Platform Providers ───────────────────────────
// Each platform gets a provider with read/write tools.
// These are starter stubs — flesh out with real API calls as you
// integrate each platform.

registerToolProvider({
  type: "twitter",
  requiredSources: ["TWITTER"],
  resolveTools: (credentials, meta) => [
    {
      name: "twitter_get_metrics",
      description: "Fetch current Twitter/X metrics for the connected account (followers, impressions, engagements, top tweets).",
      input_schema: {
        type: "object",
        properties: {
          metrics: { type: "array", items: { type: "string", enum: ["followers", "impressions", "engagements", "tweets", "mentions"] } },
          period: { type: "string", enum: ["today", "7d", "28d"] },
        },
        required: ["metrics"],
      },
      provider: "twitter",
      hasSideEffects: false,
      execute: async (input) => {
        // TODO: Implement with Twitter API v2 using credentials
        return { type: "twitter_metrics", account: meta?.accountHandle, period: input.period, note: "Twitter API integration pending" };
      },
    },
    {
      name: "twitter_post",
      description: "Post a tweet to the connected Twitter/X account. REQUIRES APPROVAL.",
      input_schema: {
        type: "object",
        properties: {
          text: { type: "string", description: "Tweet text (max 280 characters)" },
          media_urls: { type: "array", items: { type: "string" }, description: "Optional media URLs to attach" },
        },
        required: ["text"],
      },
      provider: "twitter",
      hasSideEffects: true,
      execute: async (input) => {
        // TODO: Implement with Twitter API v2
        return { type: "twitter_post", text: input.text, note: "Twitter posting integration pending" };
      },
    },
  ],
});

registerToolProvider({
  type: "steam",
  requiredSources: ["STEAM"],
  resolveTools: (credentials, meta) => [
    {
      name: "steam_get_metrics",
      description: "Fetch Steam store metrics (wishlists, page visits, reviews, player counts).",
      input_schema: {
        type: "object",
        properties: {
          metrics: { type: "array", items: { type: "string", enum: ["wishlists", "page_visits", "reviews", "players_current", "players_peak"] } },
        },
        required: ["metrics"],
      },
      provider: "steam",
      hasSideEffects: false,
      execute: async (input) => {
        return { type: "steam_metrics", appId: (credentials as any).appId, note: "Steam API integration pending" };
      },
    },
  ],
});

registerToolProvider({
  type: "discord",
  requiredSources: ["DISCORD"],
  resolveTools: (credentials, meta) => [
    {
      name: "discord_get_metrics",
      description: "Fetch Discord server metrics (member count, active users, messages per day).",
      input_schema: {
        type: "object",
        properties: {
          metrics: { type: "array", items: { type: "string", enum: ["members", "online", "messages_today", "new_members_7d"] } },
        },
        required: ["metrics"],
      },
      provider: "discord",
      hasSideEffects: false,
      execute: async (input) => {
        return { type: "discord_metrics", server: meta?.serverName, note: "Discord API integration pending" };
      },
    },
    {
      name: "discord_post_message",
      description: "Post a message to a Discord channel. REQUIRES APPROVAL.",
      input_schema: {
        type: "object",
        properties: {
          channel: { type: "string", description: "Channel name or ID" },
          content: { type: "string", description: "Message content" },
          embed: { type: "object", description: "Optional rich embed" },
        },
        required: ["channel", "content"],
      },
      provider: "discord",
      hasSideEffects: true,
      execute: async (input) => {
        return { type: "discord_post", channel: input.channel, note: "Discord API integration pending" };
      },
    },
  ],
});

registerToolProvider({
  type: "google_analytics",
  requiredSources: ["GOOGLE_ANALYTICS"],
  resolveTools: (credentials, meta) => [
    {
      name: "ga_get_metrics",
      description: "Fetch Google Analytics metrics (page views, sessions, users, bounce rate, conversions).",
      input_schema: {
        type: "object",
        properties: {
          metrics: { type: "array", items: { type: "string", enum: ["page_views", "sessions", "users", "bounce_rate", "conversions", "organic_traffic"] } },
          period: { type: "string", enum: ["today", "7d", "28d", "90d"] },
          page_filter: { type: "string", description: "Optional URL path filter" },
        },
        required: ["metrics"],
      },
      provider: "google_analytics",
      hasSideEffects: false,
      execute: async (input) => {
        return { type: "ga_metrics", property: meta?.propertyName, note: "GA4 API integration pending" };
      },
    },
  ],
});

registerToolProvider({
  type: "instagram",
  requiredSources: ["INSTAGRAM"],
  resolveTools: (credentials, meta) => [
    {
      name: "instagram_get_metrics",
      description: "Fetch Instagram metrics (followers, reach, impressions, engagement rate, top posts).",
      input_schema: {
        type: "object",
        properties: {
          metrics: { type: "array", items: { type: "string", enum: ["followers", "reach", "impressions", "engagement_rate", "top_posts"] } },
          period: { type: "string", enum: ["today", "7d", "28d"] },
        },
        required: ["metrics"],
      },
      provider: "instagram",
      hasSideEffects: false,
      execute: async (input) => {
        return { type: "instagram_metrics", account: meta?.accountHandle, note: "Instagram API integration pending" };
      },
    },
  ],
});

registerToolProvider({
  type: "app_store",
  requiredSources: ["APP_STORE_IOS"],
  resolveTools: (credentials, meta) => [
    {
      name: "appstore_get_metrics",
      description: "Fetch App Store metrics (downloads, ratings, reviews, crashes).",
      input_schema: {
        type: "object",
        properties: {
          metrics: { type: "array", items: { type: "string", enum: ["downloads", "ratings", "reviews", "crashes", "active_devices"] } },
          period: { type: "string", enum: ["7d", "28d", "90d"] },
        },
        required: ["metrics"],
      },
      provider: "app_store",
      hasSideEffects: false,
      execute: async (input) => {
        return { type: "appstore_metrics", bundleId: meta?.bundleId, note: "App Store Connect API integration pending" };
      },
    },
  ],
});
